[graph]
all-features = true

[advisories]
yanked = "warn"
ignore = [
  "RUSTSEC-2024-0413",
  "RUSTSEC-2024-0416",
  "RUSTSEC-2024-0388",
  "RUSTSEC-2025-0057",
  "RUSTSEC-2024-0412",
  "RUSTSEC-2024-0418",
  "RUSTSEC-2024-0411",
  "RUSTSEC-2024-0417",
  "RUSTSEC-2024-0414",
  "RUSTSEC-2024-0415",
  "RUSTSEC-2024-0420",
  "RUSTSEC-2024-0419",
  "RUSTSEC-2024-0384",
  "RUSTSEC-2024-0370",
  "RUSTSEC-2025-0081",
  "RUSTSEC-2025-0075",
  "RUSTSEC-2025-0080",
  "RUSTSEC-2025-0100",
  "RUSTSEC-2025-0098",
  "RUSTSEC-2024-0429",
]

[licenses]
version = 2
confidence-threshold = 0.8
allow = [
  "MIT",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "MPL-2.0",
  "CDLA-Permissive-2.0",
  "Unicode-3.0",
  "Zlib",
  "CC0-1.0",
]

[bans]
multiple-versions = "warn"
wildcards = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
